Fix tests
This reverts commit 73dc2069b1f08e7e13cdb4de852ebd40d858e8aa.

TODO:
```
FAILED test/candidate_space/test_famos.py::test_famos - TypeError: candidates...
FAILED test/pypesto/test_pypesto.py::test_pypesto - AssertionError: Series ar...
```